name: Compile Markdown to PDF
on: 
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  compile-markdown-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          #!/bin/bash
          echo "merging markdown files"
          
          cd Handbook/          
          mkdir out/
          
          for file in *.md; do
            cat "${file}" >> out/handbook.md
            echo "" >> out/handbook.md
          done
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Handbook/out
          output_dir: pdfs
          images_dir: Handbook/img
          build_html: true
      - uses: actions/upload-artifact@v1
        with:
          name: Handbook
          path: pdfs          
      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: pdfs/handbook.pdf
          body: |
            The current version of the official Squadspawn Handbook
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          tag: latest
          commit: main
          name: Squadspawn Handbook

