name: Compile Markdown to PDF
on: 
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  compile-markdown-to-pdf:
    name: Release Markdown as PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Merge Markdown files
        run: |
          #!/bin/bash
          echo "merging markdown files"
          
          cd Handbook/          
          mkdir out/
          
          for file in *.md; do
            cat "${file}" >> out/handbook.md
            echo "" >> out/handbook.md
          done
      - name: Compile Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: Handbook/out
          output_dir: pdfs
          images_dir: Handbook/img
          build_html: true
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: Handbook
          path: pdfs
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Handbook
        uses: ncipollo/release-action@v1
        with:
          artifacts: pdfs/handbook.pdf
          body: |
            The current version of the official Squadspawn Handbook
            
            ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          commit: main
          name: Squadspawn Handbook
          draft: ${{ github.ref != 'refs/heads/main' }}

